Squashed commit of ensure-all-tests-run-individually
commit bfc10ec93eb57829ceb6aa35a5b5885c4b7c81b3
Author: Chris Roos <chris@seagul.co.uk>
Date:   Thu Sep 29 11:30:21 2016 +0100

    Fix failing tests in any_instance_method_test

    I was seeing 2 failures when running the tests in this test case:

    1. AnyInstanceMethodTest#test_should_call_remove_new_method:
       Mocha::ExpectationError: unexpected invocation:
       #<Mock:0x7fe5d756b958>.reset_mocha()

    2. AnyInstanceMethodTest#test_should_call_restore_original_method:
       Mocha::ExpectationError: unexpected invocation:
       #<Mock:0x7fe5d756b840>.reset_mocha()

    The failures are all related to the fact that methods defined in
    `Mocha::ObjectMethods` weren't available in the test.

    These tests were passing when run as part of `rake test` because
    `Mocha::ObjectMethods` was being included elsewhere in the test suite.

    I ran this test case and `rake test` in Ruby versions 1.8.7, 1.9.3,
    2.0.0, 2.1, 2.2 and 2.3 after making this change. There were no
    failures.

commit 64d620f386c2e05c5e8da37f2266727d65f9345e
Author: Chris Roos <chris@seagul.co.uk>
Date:   Thu Sep 29 11:13:46 2016 +0100

    Fix failing tests in class_method_test

    I was seeing 4 failures when running the tests in this test case:

    1. ClassMethodTest#test_should_call_remove_new_method: NoMethodError:
       undefined method `reset_mocha' for #<Class:0x007fa3e00a9b38>

    2. ClassMethodTest#test_should_call_restore_original_method:
       NoMethodError: undefined method `reset_mocha' for
       #<Class:0x007fa3e00a8328>

    3. ClassMethodTest#test_should_restore_original_method_accepting_a_block_parameter:
       NoMethodError: undefined method `method_x' for #<Class:0x007fa3e009bb50>

    4. ClassMethodTest#test_should_restore_original_method
       [test/unit/class_method_test.rb:69]: Expected false to be truthy.

    The failures are all related to the fact that methods defined in
    `Mocha::ObjectMethods` weren't available in the test.

    These tests were passing when run as part of `rake test` because
    `Mocha::ObjectMethods` was being included elsewhere in the test suite.

    I ran this test case and `rake test` in Ruby versions 1.8.7, 1.9.3,
    2.0.0, 2.1, 2.2 and 2.3 after making this change. There were no
    failures.